workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      groups:
        - google_credentials

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release --target-platform android-arm,android-arm64,android-x64

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
