workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      vars:
        FLUTTER_TARGET: lib/main.dart

    scripts:
      - flutter pub get
      - flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
